// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF859YXI4W9Bmywz7JktrqdzzZcCCaeI4',
    appId: '1:679204649530:web:121732f5fed563c7041303',
    messagingSenderId: '679204649530',
    projectId: 'binge-read-2326',
    authDomain: 'binge-read-2326.firebaseapp.com',
    storageBucket: 'binge-read-2326.appspot.com',
    measurementId: 'G-PRZC5S7EQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABGakp2AFyrA3HBfNLkFI1FzDKJyuDBrM',
    appId: '1:679204649530:android:52dfb2e440218677041303',
    messagingSenderId: '679204649530',
    projectId: 'binge-read-2326',
    storageBucket: 'binge-read-2326.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW5NdKiYt4ntr3Y8S5y7hesBkh_DcdQbI',
    appId: '1:679204649530:ios:9a0de693c3c70366041303',
    messagingSenderId: '679204649530',
    projectId: 'binge-read-2326',
    storageBucket: 'binge-read-2326.appspot.com',
    iosClientId: '679204649530-gv7nhsek5t5am5joq74l0qh493i3d5jd.apps.googleusercontent.com',
    iosBundleId: 'com.example.bingeRead',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW5NdKiYt4ntr3Y8S5y7hesBkh_DcdQbI',
    appId: '1:679204649530:ios:9a0de693c3c70366041303',
    messagingSenderId: '679204649530',
    projectId: 'binge-read-2326',
    storageBucket: 'binge-read-2326.appspot.com',
    iosClientId: '679204649530-gv7nhsek5t5am5joq74l0qh493i3d5jd.apps.googleusercontent.com',
    iosBundleId: 'com.example.bingeRead',
  );
}
